/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedAppRouteImport } from './routes/_protected/_app'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as ProtectedAppWelcomeRouteImport } from './routes/_protected/_app/welcome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAppRoute = ProtectedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedAppWelcomeRoute = ProtectedAppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => ProtectedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/welcome': typeof ProtectedAppWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof ProtectedOnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/welcome': typeof ProtectedAppWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/_app': typeof ProtectedAppRouteWithChildren
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_protected/_app/welcome': typeof ProtectedAppWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/login'
    | '/auth/signup'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/auth/login'
    | '/auth/signup'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_protected'
    | '/_protected/_app'
    | '/_protected/onboarding'
    | '/auth/login'
    | '/auth/signup'
    | '/_protected/_app/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_app': {
      id: '/_protected/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedAppRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/_app/welcome': {
      id: '/_protected/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof ProtectedAppWelcomeRouteImport
      parentRoute: typeof ProtectedAppRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProtectedAppRouteChildren {
  ProtectedAppWelcomeRoute: typeof ProtectedAppWelcomeRoute
}

const ProtectedAppRouteChildren: ProtectedAppRouteChildren = {
  ProtectedAppWelcomeRoute: ProtectedAppWelcomeRoute,
}

const ProtectedAppRouteWithChildren = ProtectedAppRoute._addFileChildren(
  ProtectedAppRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedAppRoute: typeof ProtectedAppRouteWithChildren
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAppRoute: ProtectedAppRouteWithChildren,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
